---
- name: "Install Node.js"
  shell: |
    # Install Node.js LTS as as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs
    
    # Install "n" Node Package Manager globally and use Node.js v13.8.0
    sudo npm install --global n
    sudo n 13.8.0

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes

- name: "Check versions"
  shell: | 
    node --version
    npm -v
    pm2 -V