---
  - name: "update apt packages."
    become: true
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: true
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: true
    apt:
      autoremove: yes

  - name: "Add nodejs from NodeSource"
    become: true
    shell: |
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt-get install -y nodejs
      sudo npm install -g n
      sudo n 13.8.0

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes

  - name: "Check versions"
    shell: | 
      node --version
      npm -v
      pm2 -V