---
  - name: "update apt packages."
    become: true
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: true
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: true
    apt:
      autoremove: yes

  - name: "Add nodejs from NodeSource"
    become: true
    shell: |
      curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

  - name: "Install nodejs from NodeSource"
    become: true
    apt:
      name: ["nodejs"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes

  - name: "Check versions"
    shell: | 
      node --version
      npm -v
      pm2 -V